### ISSUE TITLE
Does the front-end ever call the back-end? 

### ISSUE THREAD

**Issue by r-i-c-h** [gurveerdhindsa/ref#1]
Perhaps I'm being stupid - but does the front-end React client in this repo actually make any calls to the backend firefunctions/express API?

**Comment by gurveerdhindsa** [comment]
No, in this case the frontend does not call an endpoint (though something I can implement!). 

To make calls to the backend whilst running a single session, you can run: `npm run build && firebase serve`

This will start localhost:5000 and you can execute the endpoint /v1/test at localhost:5000/v1/test.

Hope this helped!

**Comment by gurveerdhindsa** [comment]
Here's a sample request to the backend (https://github.com/gurveerdhindsa/ref/commit/509adcc052aa08894d5b921004fb750633dbaaba)
